# Index pass over vivify_examples/ -- produces a feature matrix for comparison.
# Output: structured PSObjects + markdown table written to docs/vivify-examples-index.md
# Re-run any time new examples are added to vivify_examples/.

[CmdletBinding()]
param(
    [string]$ExamplesDir,
    [string]$OutputDoc
)

$ErrorActionPreference = 'Stop'

# Resolve defaults at runtime (param-block default expressions can fail when $PSScriptRoot
# isn't populated yet under some invocation paths).
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $ExamplesDir) { $ExamplesDir = Join-Path $scriptDir '..\vivify_examples' }
if (-not $OutputDoc)   { $OutputDoc   = Join-Path $scriptDir '..\docs\vivify-examples-index.md' }

if (-not (Test-Path $ExamplesDir)) {
    throw "ExamplesDir not found: $ExamplesDir"
}

# Folder name pattern: "<ID> (<Name> - <Author>)"
# Require spaces around the separating " - " so song names like "42-flux" don't get split mid-name.
$folderRegex = '^([0-9a-f]+)\s*\((.+?)\s+-\s+(.+?)\)$'

$rows = @()

Get-ChildItem -LiteralPath $ExamplesDir -Directory | Sort-Object Name | ForEach-Object {
    $folder = $_
    $folderName = $folder.Name

    if ($folderName -match $folderRegex) {
        $id = $Matches[1]
        $songName = $Matches[2]
        $author = $Matches[3]
    } else {
        $id = '?'
        $songName = $folderName
        $author = '?'
    }

    $infoPath = Join-Path $folder.FullName 'Info.dat'
    $envName = '?'
    if (Test-Path -LiteralPath $infoPath) {
        try {
            $info = Get-Content -LiteralPath $infoPath -Raw | ConvertFrom-Json
            $envName = $info._environmentName
        } catch {
            $envName = 'PARSE_ERROR'
        }
    } else {
        $envName = 'NO_INFO'
    }

    # Bundle (only Windows2021 -- the canonical for our project, others are platform variants)
    $bundle = Get-ChildItem -LiteralPath $folder.FullName -Filter 'bundleWindows2021.vivify' -ErrorAction SilentlyContinue | Select-Object -First 1
    $bundleSizeMB = if ($bundle) { [math]::Round($bundle.Length / 1MB, 2) } else { 0 }
    $hasBundle = if ($bundle) { 'yes' } else { 'no' }

    # Difficulty .dat files (exclude Info.dat and BPMInfo.dat)
    $diffFiles = Get-ChildItem -LiteralPath $folder.FullName -Filter '*.dat' -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -ne 'Info.dat' -and $_.Name -ne 'BPMInfo.dat' }

    $allCustomEventTypes = New-Object System.Collections.Generic.HashSet[string]
    $totalCustomEvents = 0
    $usesEnvDisable = $false

    foreach ($df in $diffFiles) {
        try {
            $diff = Get-Content -LiteralPath $df.FullName -Raw | ConvertFrom-Json
        } catch {
            continue
        }

        # _customData lookup tolerant a v2 / v3
        $cd = $null
        if ($diff.PSObject.Properties.Name -contains '_customData') { $cd = $diff._customData }
        elseif ($diff.PSObject.Properties.Name -contains 'customData') { $cd = $diff.customData }

        if ($cd) {
            # _customEvents (v2) or customEvents (v3)
            $events = $null
            if ($cd.PSObject.Properties.Name -contains '_customEvents') { $events = $cd._customEvents }
            elseif ($cd.PSObject.Properties.Name -contains 'customEvents') { $events = $cd.customEvents }

            if ($events) {
                $totalCustomEvents += $events.Count
                foreach ($e in $events) {
                    $type = if ($e._type) { $e._type } elseif ($e.t) { $e.t } else { '?' }
                    $allCustomEventTypes.Add($type) | Out-Null
                }
            }

            # environment[] (Chroma env disable / customize)
            $env = $null
            if ($cd.PSObject.Properties.Name -contains 'environment') { $env = $cd.environment }
            if ($env -and $env.Count -gt 0) { $usesEnvDisable = $true }
        }
    }

    $rows += [PSCustomObject]@{
        ID            = $id
        Song          = $songName
        Author        = $author
        Env           = $envName
        Bundle        = $hasBundle
        BundleMB      = $bundleSizeMB
        CustomEvts    = $totalCustomEvents
        EventTypes    = ($allCustomEventTypes | Sort-Object) -join ', '
        EnvDisable    = if ($usesEnvDisable) { 'yes' } else { 'no' }
        Diffs         = $diffFiles.Count
    }
}

# Print to console (for live inspection)
$rows | Format-Table -AutoSize -Wrap

# Generate markdown table
$mdLines = @()
$mdLines += '<!-- AUTO-GENERATED by scripts/index-vivify-examples.ps1 -- do NOT edit by hand. Re-run the script. -->'
$mdLines += ''
$mdLines += '| ID | Song | Author | Env | Bundle (MB) | CustomEvts | Diffs | EnvDisable | Event types |'
$mdLines += '|---|---|---|---|---|---|---|---|---|'
foreach ($r in $rows) {
    $bundleCell = if ($r.Bundle -eq 'yes') { "$($r.BundleMB)" } else { '--' }
    $mdLines += "| ``$($r.ID)`` | $($r.Song) | $($r.Author) | $($r.Env) | $bundleCell | $($r.CustomEvts) | $($r.Diffs) | $($r.EnvDisable) | $($r.EventTypes) |"
}

# Write to a marker section in the doc, preserving handcrafted content above/below
$markerStart = '<!-- INDEX_TABLE_START -->'
$markerEnd = '<!-- INDEX_TABLE_END -->'
$tableBlock = $markerStart + "`n" + ($mdLines -join "`n") + "`n" + $markerEnd

if (Test-Path -LiteralPath $OutputDoc) {
    # Force UTF-8 read/write explicitly. PowerShell 5.1 default ANSI mangles UTF-8 content.
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    $existing = [System.IO.File]::ReadAllText($OutputDoc, $utf8NoBom)
    if ($existing.Contains($markerStart)) {
        $startIdx = $existing.IndexOf($markerStart)
        $endIdx = $existing.IndexOf($markerEnd) + $markerEnd.Length
        $newContent = $existing.Substring(0, $startIdx) + $tableBlock + $existing.Substring($endIdx)
        [System.IO.File]::WriteAllText($OutputDoc, $newContent, $utf8NoBom)
        Write-Host "Updated table block in $OutputDoc"
    } else {
        Write-Host "Doc exists but has no marker; appending table block."
        [System.IO.File]::AppendAllText($OutputDoc, "`n`n$tableBlock`n", $utf8NoBom)
    }
} else {
    Write-Host "Output doc not found: $OutputDoc -- write the doc skeleton first."
}
